/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DetailProductCreateNestedManyWithoutProductsInput } from "./DetailProductCreateNestedManyWithoutProductsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
} from "class-validator";
import { Type } from "class-transformer";
import { OrderDetailCreateNestedManyWithoutProductsInput } from "./OrderDetailCreateNestedManyWithoutProductsInput";
import { ServiceWhereUniqueInput } from "../../service/base/ServiceWhereUniqueInput";

@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: () => DetailProductCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => DetailProductCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => DetailProductCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  detailProducts?: DetailProductCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => OrderDetailCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => OrderDetailCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => OrderDetailCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  orderDetails?: OrderDetailCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: () => ServiceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServiceWhereUniqueInput)
  @IsOptional()
  @Field(() => ServiceWhereUniqueInput, {
    nullable: true,
  })
  service?: ServiceWhereUniqueInput | null;
}

export { ProductCreateInput as ProductCreateInput };
